In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df=pd.read_csv('Real_estate_DataCleaning_v1.csv',index_col=0)

In [3]:
df.head()

,F/H,sector,society,price,price_per_sqft,total_area(sqft),bedRoom,bathroom,balcony,additionalRoom,address,floorNum,agePossession,nearbyLocations,furnishDetails,features
0,1,81,signature global city 81,0.82,8639,949,2,2,3,0.0,"Sector 81, Sector 81 Gurgaon, Gurgaon, Haryana",2.0,undefined,"['Orris Community Center', 'HP Petrol Pump', '...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN
1,0,50,unitech nirvana birch court,11.95,36883,3240,3,3,2,"Study Room,Servant Room","Nirvana Country, Gurgaon, Haryana",1.0,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...","['1 Wardrobe', '1 Fan', '1 Geyser', '3 Light',...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
2,1,107,signature global solera,0.28,5674,493,2,2,2,0.0,"Sector 107 Gurgaon, Gurgaon, Haryana",11.0,1 to 5 Year Old,"['Gurgaon Dreamz Mall', 'Dwarka Expressway', ""...","['1 Wardrobe', '3 Fan', '5 Light', 'No AC', 'N...","['Power Back-up', 'Lift(s)', 'Maintenance Staf..."
3,0,5,NaN,3.50,14787,2367,5,4,2,"Pooja Room,Others","Sector 5 Gurgaon, Gurgaon, Haryana",2.0,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard..."
4,0,3,ashok vihar phase iii extension,0.40,8889,450,7,4,3,Pooja Room,"House No.183, Street Number 7, Ashok Vihar Pha...",4.0,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","['3 Fan', '15 Light', '1 Wardrobe', 'No AC', '...",['Water Storage']

In [5]:
df['floorNum'].value_counts()

floorNum
3.0     545
2.0     539
1.0     388
4.0     329
8.0     200
6.0     187
7.0     187
10.0    186
5.0     181
9.0     170
12.0    162
14.0    120
11.0    113
15.0     83
16.0     54
17.0     51
13.0     43
18.0     38
19.0     33
20.0     25
21.0     16
23.0     14
22.0     14
24.0     11
25.0      9
27.0      8
30.0      5
0.0       5
26.0      5
28.0      4
33.0      4
31.0      4
29.0      3
32.0      2
40.0      2
35.0      2
39.0      2
34.0      2
43.0      2
44.0      1
45.0      1
41.0      1
51.0      1
38.0      1
Name: count, dtype: int64

### ADDRESS

In [6]:
df[df['society'].isnull() & df['address'].isnull()]

,F/H,sector,society,price,price_per_sqft,total_area(sqft),bedRoom,bathroom,balcony,additionalRoom,address,floorNum,agePossession,nearbyLocations,furnishDetails,features
406,0,3,NaN,0.38,8444,450,1,1,1,0,NaN,1.0,5 to 10 Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",NaN,['Recently Renovated']
2159,0,12,NaN,1.72,11111,1548,6,3,1,Others,NaN,2.0,10+ Year Old,"['Hanuman Mandir', 'Sharma Hospital Gurgaon', ...",NaN,NaN

In [7]:
df.drop(index=[406,2159],inplace=True)

In [10]:
df[df['address'].isnull()]

,F/H,sector,society,price,price_per_sqft,total_area(sqft),bedRoom,bathroom,balcony,additionalRoom,address,floorNum,agePossession,nearbyLocations,furnishDetails,features
605,1,79,supertech araville,0.90,5883,1530,2,2,3,1.0,NaN,5.0,1 to 5 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...",[],"['Lift(s)', 'Intercom Facility', 'Security / F..."
1720,0,11,not applicable,2.20,12222,1800,4,3,2,"Pooja Room,Study Room",NaN,1.0,10+ Year Old,"['Rajiv Chowk Mosque', 'Hanuman Mandir', 'Hdfc...",[],"['Private Garden / Terrace', 'Park', 'Visitor ..."
2142,0,54,suncity township,2.00,30968,646,9,9,3,Servant Room,NaN,11.0,1 to 5 Year Old,"['Sector 54 chowk metro station', 'Sector metr...","['1 Water Purifier', '9 Fan', '1 Fridge', '1 E...",['Internet/wi-fi connectivity']
2463,1,104,hero homes,1.20,17548,684,2,2,2,0.0,NaN,22.0,23-Sep,"['Basai Metro Station', 'HUDA Market', 'Dwarka...","['4 Fan', '4 Light', 'No AC', 'No Bed', 'No Ch...","['Intercom Facility', 'Lift(s)', 'Swimming Poo..."
2759,1,3,vidya apartment,0.22,4210,523,2,2,1,1.0,NaN,1.0,1 to 5 Year Old,"['Palam triangle', 'Palam Vihar Vyapar kendra'...","['1 Water Purifier', '1 Fan', '1 Fridge', '1 E...","['Lift(s)', 'Water purifier', 'Maintenance Sta..."
2833,0,104,shri shyam residency,0.62,12400,500,3,3,1,Others,NaN,2.0,5 to 10 Year Old,"['Civil lines metro station', 'Railway metro s...","['1 Water Purifier', '4 Fan', '2 Geyser', '4 L...",['Natural Light']
3033,1,83,vatika lifestyle homes,1.30,4545,2860,3,3,1,0.0,NaN,6.0,1 to 5 Year Old,"['Sapphire 83 Mall', 'NH – 08', 'Knowledge Tre...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
3745,1,111,tashee capital gateway,0.96,6500,1477,2,2,1,1.0,NaN,4.0,23-Dec,"['Global Foyer Mall', 'Dwarka Expy, Sai Kunj, ...",NaN,"['Intercom Facility', 'Lift(s)', 'Maintenance ..."
3843,1,92,sare green parc phase 3,1.08,5150,2097,4,4,2,1.0,NaN,16.0,0 to 1 Year Old,"['Huda Metro Station', 'Sector Road', 'Delhi-J...",NaN,"['Security / Fire Alarm', 'Intercom Facility',..."

In [14]:
df.loc[2142,'address']='Sector 54, Golf Course Road, Gurugram, Haryana'
df.loc[2463,'address']='Sector 104, along the Dwarka Expressway, Gurugram, Haryana'
df.loc[3033,'address']='Vatika India Next, Sector 83, Gurugram, Haryana'
df.loc[3745,'address']='Sector 111, Dwarka Expressway, Gurugram'
df.loc[3843,'address']='Sector 92, Gurgaon, Haryana'
df.drop(index=[2833,2759,1720],inplace=True)

In [13]:
df[df['society']=='supertech araville']

,F/H,sector,society,price,price_per_sqft,total_area(sqft),bedRoom,bathroom,balcony,additionalRoom,address,floorNum,agePossession,nearbyLocations,furnishDetails,features
128,1,79,supertech araville,0.71,6061,1171,2,2,3,1.0,"E 1706, Sector 79 Gurgaon, Gurgaon, Haryana",17.0,0 to 1 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","['2 Wardrobe', '2 Geyser', '1 Light', '2 AC', ...","['Intercom Facility', 'Lift(s)', 'Maintenance ..."
319,1,79,supertech araville,0.78,6024,1295,2,2,3,1.0,"Sector 79 Gurgaon, Gurgaon, Haryana",NaN,0 to 1 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...",[],"['Lift(s)', 'Feng Shui / Vaastu Compliant', 'I..."
605,1,79,supertech araville,0.90,5883,1530,2,2,3,1.0,"Sector 79, Naurangpur, Gurugram, Haryana, 1220...",5.0,1 to 5 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...",[],"['Lift(s)', 'Intercom Facility', 'Security / F..."
800,1,79,supertech araville,0.71,5522,1286,2,2,0,0.0,"E906, Sector-79, Sector 79 Gurgaon, Gurgaon, H...",9.0,Under Construction,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...",[],NaN
1359,1,79,supertech araville,1.45,7455,1945,3,3,3,0.0,"Sector 79 Gurgaon, Gurgaon, Haryana",3.0,1 to 5 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","['3 Wardrobe', '2 Geyser', '2 AC', 'No Bed', '...",NaN
1767,1,79,supertech araville,0.78,6023,1295,2,2,3,0.0,"Sector 79 Gurgaon, Gurgaon, Haryana",17.0,1 to 5 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","['1 Wardrobe', '1 Light', '1 AC', 'No Bed', 'N...","['Power Back-up', 'Lift(s)', 'Swimming Pool', ..."
1880,1,79,supertech araville,1.35,9000,1500,2,2,3,2.0,"Naurangpur, Delhi-Jaipur Highway, Sector 79 Gu...",6.0,0 to 1 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2121,1,79,supertech araville,0.80,6178,1295,2,2,3,1.0,"E-906, Sector 79 Gurgaon, Gurgaon, Haryana",9.0,0 to 1 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...",[],"['Lift(s)', 'Swimming Pool', 'Park', 'Club hou..."
2280,1,79,supertech araville,0.71,6061,1171,2,2,3,1.0,"E 1706, Sector 79 Gurgaon, Gurgaon, Haryana",17.0,0 to 1 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","['2 Wardrobe', '2 Geyser', '1 Light', '2 AC', ...","['Intercom Facility', 'Lift(s)', 'Maintenance ..."
2539,1,79,supertech araville,0.83,5424,1530,2,2,3,1.0,"Sector 79 Gurgaon, Gurgaon, Haryana",5.0,0 to 1 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","['1 Water Purifier', '2 Fan', '1 Fridge', '1 E...","['Feng Shui / Vaastu Compliant', 'Security / F..."
2610,1,79,supertech araville,1.10,5641,1950,3,3,3,0.0,"401, Sector 79 Gurgaon, Gurgaon, Haryana",1.0,1 to 5 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","['3 Fan', '1 Exhaust Fan', '2 Geyser', '3 Ligh...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2889,1,79,supertech araville,1.00,6535,1530,2,2,3,1.0,"Sector 79 Gurgaon, Gurgaon, Haryana",4.0,1 to 5 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","['2 Geyser', '1 AC', 'No Bed', 'No Chimney', '...","['Security / Fire Alarm', 'Intercom Facility',..."
2989,1,79,supertech araville,0.95,6209,1530,2,2,3,1.0,"Sector 79 Gurgaon, Gurgaon, Haryana",7.0,0 to 1 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","['1 Fan', '1 Geyser', '1 Light', 'No AC', 'No ...","['Feng Shui / Vaastu Compliant', 'Security / F..."
3265,1,79,supertech araville,1.35,6940,1945,3,3,3,0.0,"Sector 79 Gurgaon, Gurgaon, Haryana",4.0,1 to 5 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","['1 Water Purifier', '2 Fan', '1 Geyser', '3 L...",NaN
3640,1,79,supertech araville,0.95,6209,1530,2,2,3,1.0,"Sector 79 Gurgaon, Gurgaon, Haryana",7.0,0 to 1 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","['1 Fan', '1 Geyser', '1 Light', 'No AC', 'No ...","['Feng Shui / Vaastu Compliant', 'Security / F..."
3838,1,79,supertech araville,0.90,6950,1295,2,2,0,0.0,"Sector 79, Gurgaon Haryana, Sector 79 Gurgaon,...",12.0,undefined,NaN,NaN,NaN
3888,1,79,supertech araville,0.80,5266,1519,2,2,2,1.0,"Sector 79 Gurgaon, Gurgaon, Haryana",12.0,0 to 1 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","['1 Wardrobe', '1 Fan', '1 Light', '1 AC', '1 ...","['Feng Shui / Vaastu Compliant', 'Security / F..."

In [12]:
df.loc[605,'address']='Sector 79, Naurangpur, Gurugram, Haryana, 122004, India'

In [15]:
df[df['address'].isnull()]  ## Removed and modifies all missing values in address

Empty DataFrame
Columns: [F/H, sector, society, price, price_per_sqft, total_area(sqft), bedRoom, bathroom, balcony, additionalRoom, address, floorNum, agePossession, nearbyLocations, furnishDetails, features]
Index: []

In [16]:
df['society'].isnull().sum()

550

### Age Possession

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3904 entries, 0 to 3908
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   F/H               3904 non-null   int64
 1   sector            3899 non-null   object
 2   society           3354 non-null   object
 3   price             3904 non-null   float64
 4   price_per_sqft    3904 non-null   int64
 5   total_area(sqft)  3904 non-null   int64
 6   bedRoom           3904 non-null   int64
 7   bathroom          3904 non-null   int64
 8   balcony           3904 non-null   int64
 9   additionalRoom    3904 non-null   object
 10  address           3904 non-null   object
 11  floorNum          3748 non-null   float64
 12  agePossession     3903 non-null   object
 13  nearbyLocations   3708 non-null   object
 14  furnishDetails    2888 non-null   object
 15  features          3215 non-null   object
dtypes: float64(2), int64(6), object(8)
memory usage: 518.5+ KB

In [51]:
df['agePossession'].value_counts()

agePossession
1 to 5 Year Old       1686
5 to 10 Year Old       599
0 to 1 Year Old        543
undefined              354
10+ Year Old           345
within 1 year          152
Under Construction      87
Within 6 months         69
within 2-3 years        42
Within 3 months         26
Name: count, dtype: int64

In [41]:
index_list=df[df['agePossession'].str.contains('-',na=False,case=False)].index.tolist()

In [44]:
index_list

[15,
 52,
 56,
 57,
 69,
 93,
 94,
 104,
 111,
 157,
 193,
 227,
 249,
 311,
 348,
 374,
 385,
 442,
 444,
 463,
 488,
 519,
 576,
 615,
 639,
 685,
 698,
 699,
 783,
 813,
 922,
 929,
 955,
 972,
 1045,
 1068,
 1189,
 1241,
 1242,
 1243,
 1246,
 1250,
 1262,
 1378,
 1414,
 1467,
 1503,
 1504,
 1520,
 1541,
 1558,
 1575,
 1597,
 1607,
 1618,
 1632,
 1642,
 1697,
 1703,
 1741,
 1763,
 1769,
 1785,
 1788,
 1856,
 1876,
 1899,
 1932,
 1966,
 1994,
 2010,
 2021,
 2055,
 2062,
 2149,
 2158,
 2172,
 2190,
 2197,
 2202,
 2208,
 2217,
 2249,
 2277,
 2359,
 2390,
 2393,
 2410,
 2459,
 2463,
 2512,
 2564,
 2565,
 2613,
 2649,
 2693,
 2694,
 2735,
 2744,
 2745,
 2752,
 2760,
 2805,
 2865,
 2866,
 2869,
 2890,
 2912,
 2927,
 2969,
 2976,
 2994,
 3057,
 3060,
 3067,
 3084,
 3105,
 3109,
 3148,
 3180,
 3206,
 3223,
 3225,
 3240,
 3279,
 3282,
 3293,
 3319,
 3350,
 3364,
 3393,
 3432,
 3454,
 3516,
 3525,
 3561,
 3574,
 3576,
 3606,
 3626,
 3651,
 3699,
 3707,
 3721,
 3726,
 3730,
 3732,
 3745,
 3798,
 3803,
 3832,
 3859]

In [48]:
df.loc[index_list,'agePossession']='within 1 year'

In [50]:
df.loc[df[df['agePossession'].str.contains('By',na=False,case=False)].index.tolist(),'agePossession']='within 2-3 years'

In [53]:
df.reset_index(inplace=True)

### Floor Num

In [54]:
df['floorNum'].value_counts()

floorNum
3.0     545
2.0     537
1.0     385
4.0     329
8.0     200
6.0     187
7.0     187
10.0    186
5.0     181
9.0     170
12.0    162
14.0    120
11.0    113
15.0     83
16.0     54
17.0     51
13.0     43
18.0     38
19.0     33
20.0     25
21.0     16
23.0     14
22.0     14
24.0     11
25.0      9
27.0      8
30.0      5
0.0       5
26.0      5
28.0      4
33.0      4
31.0      4
29.0      3
32.0      2
40.0      2
35.0      2
39.0      2
34.0      2
43.0      2
44.0      1
45.0      1
41.0      1
51.0      1
38.0      1
Name: count, dtype: int64

### Society

In [78]:
df[(df['society'].isnull()) & (df['F/H']==0)]

,index,F/H,sector,society,price,price_per_sqft,total_area(sqft),bedRoom,bathroom,balcony,additionalRoom,address,floorNum,agePossession,nearbyLocations,furnishDetails,features
3,3,0,5,NaN,3.50,14787,2367,5,4,2,"Pooja Room,Others","Sector 5 Gurgaon, Gurgaon, Haryana",2.0,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard..."
25,25,0,12,NaN,2.00,14954,1337,3,1,0,0,"Manesar, Gurgaon, Haryana",3.0,5 to 10 Year Old,"['Dr. Sahil Clinic', 'Pooja Clinic', 'Yadav De...",[],"['Private Garden / Terrace', 'Water Storage']"
26,26,0,12,NaN,6.00,315789,190,9,6,2,0,"Near Sadar Bazar Gurgaon, Jacobpura, Gurgaon, ...",2.0,10+ Year Old,"['Hanuman Mandir', 'Rajiv Memorial Eye Infirma...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN
27,27,0,55,NaN,5.00,44444,1125,9,9,3,Others,"Sector 55 Gurgaon, Gurgaon, Haryana",5.0,0 to 1 Year Old,"['Sector metro station', 'Sector metro station...","['14 Fan', '9 Geyser', '17 Light', '10 AC', '9...","['Private Garden / Terrace', 'Maintenance Staf..."
28,28,0,11,NaN,3.50,15555,2250,10,1,0,0,"Shivaji Nagar, Sector 11, Gurgaon, Sector 11 G...",1.0,0 to 1 Year Old,"['Rajiv Chowk Mosque', 'Hanuman Mandir', 'Stat...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3868,3873,0,12,NaN,0.38,4222,900,3,3,3,0,"Jacobpura, Gurgaon, Haryana",3.0,1 to 5 Year Old,"['Hanuman Mandir', 'Rajiv Memorial Eye Infirma...",[],NaN
3886,3891,0,49,NaN,4.45,15451,2880,6,6,3,"Pooja Room,Study Room,Servant Room,Store Room","Uppals Southend, Gurgaon, Haryana",3.0,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","['1 Water Purifier', '6 Fan', '1 Fridge', '1 E...","['Centrally Air Conditioned', 'Water purifier'..."
3890,3895,0,7,NaN,0.45,5000,900,3,2,0,0,"Baldev Nagar, Sector 9, Baldev Nagar, Gurgaon,...",1.0,undefined,"['Ankur Clinic and Maternity Home', 'Navjeevan...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN
3898,3903,0,8,NaN,0.63,7875,800,4,2,1,Others,"H No 375/16, Near Anandpur Kutia, New Basti, G...",2.0,10+ Year Old,NaN,NaN,['Water Storage']
3899,3904,0,43,NaN,5.75,29716,1935,4,4,2,"Servant Room,Pooja Room,Store Room","C Block Sushant Lok Phase 1, Gurgaon, Haryana",2.0,10+ Year Old,"['Sector 42-43 metro station', 'Huda city cent...",NaN,"['Feng Shui / Vaastu Compliant', 'High Ceiling..."

In [70]:
df['society'].isnull().sum()

550

In [84]:
df['society']=df['society'].fillna('indepedent')

In [85]:
df['society'].isnull().sum()

0

### Furnish Details

In [83]:
df['furnishDetails'].value_counts()

furnishDetails
Unfurnished                                                                                                                                                                                                                                                             1016
[]                                                                                                                                                                                                                                                                       431
['1 Light', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Fan', 'No Geyser', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']     208
['1 Modular Kitchen', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Fan', 'No Geyser', 'No Light', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']      74
['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Geyser', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']        65
                                                                                                                                                                                                                                                                        ...
['3 Wardrobe', '2 Geyser', '2 AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Fan', 'No Modular Kitchen', 'No Light', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']         1
['4 Fan', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Geyser', 'No Modular Kitchen', 'No Light', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']       1
['1 Light', '1 Modular Kitchen', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Fan', 'No Geyser', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']        1
['6 Fan', '1 Exhaust Fan', '3 Geyser', '8 Light', '5 AC', '1 Chimney', '1 Curtains', '1 Modular Kitchen', '3 Wardrobe', 'No Bed', 'No Dining Table', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']               1
['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Geyser', '10 Light', '6 AC', '1 Chimney', '1 Modular Kitchen', 'No Bed', 'No Curtains', 'No Dining Table', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']             1
Name: count, Length: 1829, dtype: int64

In [82]:
df['furnishDetails']=df['furnishDetails'].fillna('Unfurnished')

In [86]:
df['features'].value_counts()

features
['Feng Shui / Vaastu Compliant', 'Security / Fire Alarm', 'Intercom Facility', 'Lift(s)', 'Maintenance Staff', 'Water Storage', 'Park', 'Visitor Parking']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              286
['Centrally Air Conditioned', 'Water purifier', 'Security / Fire Alarm', 'Feng Shui / Vaastu Compliant', 'Private Garden / Terrace', 'Intercom Facility', 'Lift(s)', 'High Ceiling Height', 'Maintenance Staff', 'False Ceiling Lighting', 'Water Storage', 'Separate entry for servant room', 'No open drainage around', 'Bank Attached Property', 'Piped-gas', 'Internet/wi-fi connectivity', 'Recently Renovated', 'Visitor Parking', 'Swimming Pool', 'Park', 'Security Personnel', 'Natural Light', 'Airy Rooms', 'Spacious Interiors', 'Low Density Society', 'Waste Disposal', 'Rain Water Harvesting', 'Water softening plant', 'Shopping Centre', 'Fitness Centre / GYM', 'Club house / Community Center']                      91
['Centrally Air Conditioned', 'Water purifier', 'Security / Fire Alarm', 'Power Back-up', 'Feng Shui / Vaastu Compliant', 'Private Garden / Terrace', 'Intercom Facility', 'Lift(s)', 'High Ceiling Height', 'Maintenance Staff', 'False Ceiling Lighting', 'Water Storage', 'Separate entry for servant room', 'No open drainage around', 'Bank Attached Property', 'Piped-gas', 'Internet/wi-fi connectivity', 'Recently Renovated', 'Visitor Parking', 'Swimming Pool', 'Park', 'Security Personnel', 'Natural Light', 'Airy Rooms', 'Spacious Interiors', 'Low Density Society', 'Waste Disposal', 'Rain Water Harvesting', 'Water softening plant', 'Shopping Centre', 'Fitness Centre / GYM', 'Club house / Community Center']     64
['Security / Fire Alarm', 'Intercom Facility', 'Lift(s)', 'Maintenance Staff', 'Water Storage', 'Park', 'Visitor Parking']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               47
['Feng Shui / Vaastu Compliant', 'Private Garden / Terrace', 'Maintenance Staff', 'Water Storage', 'Park', 'Visitor Parking', 'Waste Disposal', 'Rain Water Harvesting']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 38
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ...
['Centrally Air Conditioned', 'Water purifier', 'Security / Fire Alarm', 'Power Back-up', 'Feng Shui / Vaastu Compliant', 'Private Garden / Terrace', 'Intercom Facility', 'Lift(s)', 'Maintenance Staff', 'False Ceiling Lighting', 'Water Storage', 'Separate entry for servant room', 'No open drainage around', 'Bank Attached Property', 'Piped-gas', 'Internet/wi-fi connectivity', 'Recently Renovated', 'Visitor Parking', 'Swimming Pool', 'Park', 'Security Personnel', 'Natural Light', 'Airy Rooms', 'Low Density Society', 'Waste Disposal', 'Rain Water Harvesting', 'Water softening plant', 'Shopping Centre', 'Fitness Centre / GYM', 'Club house / Community Center']                                                   1
['Feng Shui / Vaastu Compliant', 'Private Garden / Terrace', 'Maintenance Staff', 'Park', 'Bank Attached Property', 'Club house / Community Center']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
['Power Back-up', 'Intercom Facility', 'Lift(s)', 'Swimming Pool', 'Park', 'Piped-gas', 'Internet/wi-fi connectivity', 'Shopping Centre', 'Fitness Centre / GYM', 'Club house / Community Center', 'Water softening plant']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
['Centrally Air Conditioned', 'Water purifier', 'Security / Fire Alarm', 'Power Back-up', 'Feng Shui / Vaastu Compliant', 'Intercom Facility', 'Lift(s)', 'High Ceiling Height', 'Maintenance Staff', 'Water Storage', 'Separate entry for servant room', 'No open drainage around', 'Internet/wi-fi connectivity', 'Recently Renovated', 'Visitor Parking', 'Swimming Pool', 'Park', 'Security Personnel', 'Natural Light', 'Airy Rooms', 'Spacious Interiors', 'Waste Disposal', 'Rain Water Harvesting', 'Water softening plant', 'Shopping Centre', 'Fitness Centre / GYM', 'Club house / Community Center']                                                                                                                          1
['Power Back-up', 'Lift(s)', 'Swimming Pool', 'Maintenance Staff', 'Park', 'Shopping Centre', 'Fitness Centre / GYM', 'Club house / Community Center', 'Water softening plant']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1
Name: count, Length: 1871, dtype: int64

### WE HAVE TO DO FEATURE ENG ON furnishDetails(classify in semifurnish,furnished) , features(convert it into type of luxury on basis of features),agePossession(new, relatively new,old,moderately old,under construction),additional rooms

In [88]:
df.drop(columns=['index'],inplace=True)

In [89]:
df.sample()

,F/H,sector,society,price,price_per_sqft,total_area(sqft),bedRoom,bathroom,balcony,additionalRoom,address,floorNum,agePossession,nearbyLocations,furnishDetails,features
3292,1,33,godrej nature plus,1.55,9955,1557,3,2,3,0.0,"Sector-33 Sohna, Gurgaon, Haryana",8.0,Within 6 months,"['Signature Global Infinity Mall Sohna', 'Bads...",[],"['Feng Shui / Vaastu Compliant', 'Security / F..."

In [91]:
df.to_csv('Real_estate_DataCleaning_v2.csv',index=False)